Repository cloudfoundry/docs-bosh, pull requests merged in 2019-08, with the labels that each got.

#671 Add type flag to incorrect cli command
  content/guide-ipv6-on-vsphere.md
Labels: in progress

#668 Add `duration` to certificate generation information
  content/director-certs.md
Labels: unscheduled

#673 Tasks output headers changed
  content/cli-v2.md
Labels: unscheduled

#669 Add disabling section to the bosh dns documentation
  content/dns.md
Labels: unscheduled

#674 Add documentation around `--no-converge` flag on lifecycle commands
  content/cli-v2.md
  content/deployment-convergence.md
Labels: unscheduled

#670 Clarify peristent disk behavior when a VM is deleted
  content/persistent-disks.md
Labels: delivered

#677 Document new `clean-up` behavior on releases on cloud configs
  content/cli-v2.md
Labels: unscheduled

#676 Remove redundant flag word, for each flag of the cli v2 documentation
  content/cli-v2.md
Labels: unscheduled

#678 🐞 Debugging Director DB has correct path
  content/tips.md
Labels: in progress

#675 Update manifest-v2.md
  content/manifest-v2.md
Labels: unscheduled

#679 Add duration option for certificate variables
  content/variable-types.md
Labels: in progress
