Repository cloudfoundry/docs-bosh, pull requests merged in 2019-11, with the labels that each got.

#696 Fix outdated field name in manifest-v2
  content/manifest-v2.md
Labels: accepted

#695 Ntp configuration 168843909
  content/ntp-config.md
  mkdocs.yml
Labels: unscheduled

#693 Update blobstore/Nats CA rotations with cleanup steps
  content/blobstore-ca-rotation.md
  content/nats-ca-rotation.md
Labels: delivered

#697 mention deployment tags in set_vm_metadata
  content/cpi-api-v1-method/set-vm-metadata.md
Labels: unscheduled

#665 Add note to job lifecycle for vm reboot
  content/job-lifecycle.md
Labels: unscheduled
